apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsocket-requester
  labels:
    app: rsocket-requester
spec:
  replicas: 1
  template:
    metadata:
      name: rsocket-requester
      labels:
        app: rsocket-requester
    spec:
      containers:
        - name: rsocket-requester
          image: rsocket-requester:latest
          ports:
            - containerPort: 8180
          imagePullPolicy: IfNotPresent
          env:
            - name: RSOCKET_BROKERS
              value: "tcp://rsocket-broker.rsocket.svc.cluster.local:9999"
      restartPolicy: Always
  selector:
    matchLabels:
      app: rsocket-requester
